### PR TITLE
Merge blurrs #34

### LINKED ISSUE #34: Rectangles are visible when using frame_memory larger than 0
(using the fixed frame memory code from after #33)

examples with each the same frame:
frame_memory == 0 on the left, frame_memory == 1 in the middle, frame_memory == 2 on the right
image two ellipses image

there is some kind of hard or obvious border that aligns with the pixel grid

same happens with plates:
image image image

### PR DESCRIPTION
**Pull request by joshinils**
change applying blurrs to using masks
two masks, one with less blurr than the other.
each mask contains a union of all detections per frame.

this way all detections which overlap (from this frame or previous frames)
will look the same amount of blurred at the end.
so no overlaps are blurred twice or more and thus creating visible artifacts.

closes #34

### CODE REVIEW

**Comment by joshinils** [comment]
sorry, this includes the commits from #30 
but has nothing to do with it.

there is a slight visible border between the inner and outer blur, but that was there previously aswell.
i guess any compression and youtube make that go away completely

**Comment by joshinils** [comment]
old:
image two ellipses image
image image image


with my changes ans using a gaussian blur:
image image image

image image image

**Comment by joshinils** [comment]
only problem could be, that now the strength of blurring is different since the gaussian blur works different to a [box blur kernel](https://en.wikipedia.org/wiki/Box_blur), but in my opinion looks much better.
i also had to change how the input parameter is used, since the gaussian blur needs an odd size:
https://github.com/tfaehse/DashcamCleaner/blob/7450118fba1159aec17495ee38af74a7da2b9aa4/dashcamcleaner/src/blurrer.py#L44
old:
https://github.com/tfaehse/DashcamCleaner/blob/ad3039aeed42b5ba53769282763e844cf8b6f360/dashcamcleaner/src/blurrer.py#L38

**Comment by joshinils** [comment]
in theory it is possible to use different blurs for the first and second mask, if you wanted, so a weak box blur for the outer blur, and a nicer looking gaussian for the inner box

**Comment by joshinils** [comment]
|`-b`|3|4|5|6|7|8|9|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|gauss size|7|9|11|13|15|17|19|
|gauss|image|image|image|image|image|image|image|
|old w/ box|image|image|image|image|image|image|image|

of course the old version still has the off by one error regarding the detections age, so here it also uses the previous detection too, and thus blurs parts of the face multiple times.

**Review by tfaehse — APPROVED** [review]

**Pull request merged**
